### ISSUE TITLE
/finishQuiz route in student.js causing db to override the old array 

### ISSUE THREAD

**Issue by ZehraRiz** [tommcandrew/quiz-master#102]
When /finishQuiz is reached, it changes _score.quizCompleted = true;_ and is supposed to alter the db too. It however overrides the the previous entries in the array and only the current one is saved. I think there's something wrong with the mongodb command that I'm using.

quiz-master/backend/routes/student.js  line no. 124

**Comment by tommcandrew** [comment]
"overrides the the previous entries in the array"

The quizScores array? I just made a quiz, invited 2 students, did the quiz twice and an object was added to quizScores for each. 

![image](https://user-images.githubusercontent.com/42588609/89118131-33a9b200-d49b-11ea-8c34-618f6618e0de.png)

**Comment by ZehraRiz** [comment]
ok thanks
