### ISSUE TITLE
Generate invite code in Share component before publishing. 

### ISSUE THREAD

**Issue by tommcandrew** [tommcandrew/quiz-master#20]
If we stick with using an invite code for students to log in with, the code needs to be unique to the student and one quiz. This would mean generating a random id/password in the Invite component when adding contacts. Both the contact id and this random invite id could be saved on an object in the Quiz invites array. 

The alternative is to make students register the conventional way.

**Comment by ZehraRiz** [comment]
I like the prefer the first option. (if it doesn't have technical issues).
Because we decided that the app should be more "teacher-oriented" 

The traditional user authentication is time consuming to make
