### ISSUE TITLE
User should be notified if a group is empty

### ISSUE THREAD

**Issue by tommcandrew** [tommcandrew/quiz-master#58]
Currently, a group can be left empty if all the contacts are deleted. I think this is ok but the user should be informed - either after they delete the last contact or maybe just if they try to add this group to QuizInvites.

**Comment by ZehraRiz** [comment]
I added a line on the groupsScreen telling the user that this group is empty. Click to add members.

Also when users edit a group and remove all members from it, They get a warning saying that its not recommeneded to have an empty group.

However, On createGroup I did not allow a user to create a group with no members in it. 
Should I remove this validation check?
