### ISSUE TITLE
A component for teacher to view quiz statistics

### ISSUE THREAD

**Issue by ZehraRiz** [tommcandrew/quiz-master#66]
Major functionality missing and hasn't been discussed yet.

If we decide to remove the quizUpdate button, we can change it to "View details" and get a component where we can see the questions in a nice format and some statistical data

**Comment by tommcandrew** [comment]
Yea great. What statistics should be included?

I'm quite keen to try using a graph/data visualisation library. Maybe we could have a graph showing results of those who have attempted the quiz.
