### ISSUE TITLE
Deleting a quiz should remove that quiz Id from user.quizzes[] in the db

### ISSUE THREAD

**Issue by ZehraRiz** [tommcandrew/quiz-master#76]

**Comment by ZehraRiz** [comment]
Simmilarly, when a contact is deleted, should we delete it from any groups it was in? Or if its a part of any quizInvites array

**Comment by tommcandrew** [comment]
I think they're already removed from any groups. I guess their invites should also be removed yea.

**Comment by ZehraRiz** [comment]
Yes I saw, deleting a contact was automatically deleting it from the groups screen as well.
